version: '2'

services:
    fhem:
        restart: always
        hostname: fhem
        domainname: docker.local
        expose:
            - "8083"
            - "7072"
        ports:
            - "8083:8083"
            - "7072:7072"
        build: fhem
        privileged: true
        volumes:
            - ./fhem/core/:/opt/fhem/
            # used to communicate between fhem and motion-eye
            # @TODO find better solution
            - ../../share/:/opt/share/
        networks:
            - fhem-network
        depends_on:
            - "mysql"
            - "mqtt"

    sonos:
        restart: always
        hostname: sonos-fhem
        domainname: docker.local
        expose:
            - "4711"
        ports:
            - "4711:4711"
        build: sonos
        volumes:
            - ./fhem/core/:/opt/fhem/ 
        network_mode: "host"
        depends_on:
            - "fhem"

    homebridge:
        restart: always
        expose:
            - "51826"
            - "8282"
            - "5353"
        ports:
            - "51826:51826"
            - "8282:8282"
            - "5353:5353"
        build: homebridge
        volumes:
            - ./homebridge/start.sh:/root/start.sh
            - ./homebridge/config.json:/root/.homebridge/config.json
        networks:
            - fhem-network
        depends_on:
            - "fhem"

    habridge:
        restart: always
        build: habridge
        network_mode: host

    mysql:
        restart: always
        hostname: mysql-fhem
        domainname: docker.local
        expose:
            - "3306"
            - "33060"
        ports:
            - "3306:3306"
            - "33060:33060"
        image: mysql/mysql-server:5.7
        volumes:
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
            - ./mysql/data:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        networks:
            - fhem-network

    mqtt:
        restart: always
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        image: toke/mosquitto
        networks:
            - fhem-network
        volumes:
            - ./mqtt/config/:/mqtt/config/
            - ./mqtt/log/:/mqtt/log/
            - ./mqtt/data/:/mqtt/data/

    nodered:
        restart: always
        expose:
            - "1880"
        ports:
            - "1880:1880"
        image: nodered/node-red-docker:0.17.5
        volumes:
            - ./nodered/data/:/data/
        networks:
            - fhem-network
        depends_on:
            - "mqtt"

    collectord:
        restart: always
        hostname: collectord-fhem
        domainname: docker.local
        expose:
            - "5222"
        ports:
            - "5222:5222"
        build: collectord
        volumes:
            - ./collectord/config/:/opt/collectord/
        networks:
            - fhem-network

networks:
    fhem-network:
        driver: bridge
